# Generated by Django 5.0.6 on 2024-06-18 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0003_alter_car_drivers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={
                "ordering": ("model",),
                "verbose_name": "car",
                "verbose_name_plural": "cars",
            },
        ),
    ]
